# This workflow checks out code, performs an Anchore container image
# vulnerability and compliance scan, and integrates the results with
# GitHub Advanced Security code scanning feature.  For more information on
# the Anchore scan action usage and parameters, see
# https://github.com/anchore/scan-action.  For more information on
# Anchore container image scanning in general, see
# https://docs.anchore.com.

name: Anchore Container Scan

on: push

jobs:
  Anchore-Build-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build local container
        uses: docker/build-push-action@v2
        with:
          tags: localbuild/testimage:latest
          push: false
          load: true

      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: "localbuild/testimage:latest"
